-- Seed the database with the starting content. Run once after schema.sql.
-- Safe to skip if you'd rather add everything through the admin dashboard.

insert into public.classes (title, dance_form, level, day, time, duration, instructor, room, instructor_image, sort_order, featured, blurb, image) values
('Kathak Fundamentals','kathak','beginner','Monday','08:00 AM','90 Mins','Guru Anjali Sharma','Studio A','https://lh3.googleusercontent.com/aida-public/AB6AXuA-NIjHiJh9oGCSr1MOibUU7e5pPXIIu-XtFPamGasfJBR4iQWRYWBNFJpdWHwLXYWPvp3hRz9A98nJdQdl9QBUEd9dArld6N4PsYe4ZogEdHkNSuXrgIwZFcNrcxiCPjDbgDhUZB-TzANAJFXhX45OWHGnP52-sitkESmFgFpY9v3Sqq-C-cCtBinsyU4Sprql7BWDXXBrWJWx-UNjpGsWSaUkKvNw-KvjcDQn-zpd1LogKEUSI61kcUqegL2b6pdOh6rZKIjw78nX',1,false,null,null),
('Bharatanatyam Nuances','bharatanatyam','intermediate','Monday','10:30 AM','120 Mins','Sri Ramesh Iyer','Main Hall','https://lh3.googleusercontent.com/aida-public/AB6AXuCWBdIWBDI5y9i4v84gLz9S8T8PV7yBD9GBfkql5ZCPPZwTsb8TwEbpIQO8B5ouBN98RBDMHlnU-09N8zVGDsJV1ss5R1QJBzmOau60FOcQmWJ80GSNbZ4qXGJVBAHAt6_rYdp5hgVg3E95FOOgTKx03u5kGPMvlyu-Zww18nzlWAvTjtAAgJqwO4pclMCk6gojBWewyhWbXC3iha9RhON0nH69GG0OTBpgbCc_zyDosSLYrSWXlbSfFwoJ-YVdLgVcQ7gmAMfuWunM',2,false,null,null),
('Odissi Choreography','odissi','advanced','Tuesday','05:00 PM','120 Mins','Meera Das','Studio B',null,1,false,null,null),
('Rhythm & Abhinaya Workshop','all','all','Tuesday','Weekend','Intensive','Masterclass Series','Main Hall',null,2,true,'A special intensive weekend workshop focusing on expressions and intricate rhythmic patterns. Open to intermediate and advanced students across all disciplines.','https://lh3.googleusercontent.com/aida-public/AB6AXuCaqAcjaW7gxVqnXJ82eTg5qjGarwmrWbxAB-nxV0TBXZ3-RCF-M-18WZUJvqZ5tUGajO3-u_A1EFb5Cgk-LFCT6bw4nncM-U2NEUZEeEn50VrWx8yCe3ELeZGxvQYszpQQzL4Oyz1iZhC0PDTK-mGEVmafggeQgLqseYXWJFqEBQGhb8ibO8KGnjEhFLhrOIPt32SwMIjQ2dVHZwKSqXQlESzOcRYQO4x3D7y_hsp7XuVLyidqonK6CfDSSbIBGxzBG5hg5cWh-7gv');

insert into public.instructors (name, title, photo, sort_order) values
('Dr. Anjali Desai','Founder & Artistic Director','https://lh3.googleusercontent.com/aida-public/AB6AXuBdwafMq-5XinvlZOwJ0KIpTaXVaKlg-KH0ZGuq9JnGQbFYrrVLbQQOVe0mbc2WmlV9P7-qPT3tC2NVahGDxPRnH6N5XYEdpYlNSBQ2-jwKpXCPKJ1DWn35oXTVBSSSa1vnrpFoV9QYFNaxkmLnp_Q-rmUuIxNO911QQmjmAwdyvBexfGpmixcrEVoUANaZL1wQOSlhv270W2L510gBVV-uwfsYxGapRzmbe1yIKTXjU6SFvhmmxcxZcITc9VLwotroB9NqCDRSqhiB',1),
('Karthik Iyer','Master of Rhythm','https://lh3.googleusercontent.com/aida-public/AB6AXuCdfShbWtE_EW_FOa6LD5VA1ypaqmjGyQ4uEFmlngoYa9qfOSBwCZcsSZtOypWLCkVEIjsgqYRputlFeGQ_E1sCFG122xwONNTl0pEOKI4dc6XGXtK_XmO_uHRF-p5pcknkfjRxeWPRaJYytsoMq4hz7h2HqXXHinx6rLoJtqrLeo3D2Xjih7UqHRBkGID_OLB2UHM3CCFq4etnXbPRk9--WMgRvRgdpj239BndCerHg51NrdnmEqSd9lHq67s-XjU94wGGja9DxX5T',2),
('Meera Krishnan','Senior Faculty','https://lh3.googleusercontent.com/aida-public/AB6AXuBm1tTfVnl5AxPopM4dQxVEWWmNxHOqlHmsqgvk2QPqmch25lv6ckcKTw2ei7xHj7n9RWEtZTq7BKPJHdwIiIM72TDYjbxLuzyjYUG75G_ifAcuW1TZOC7C9ux6xUcyiUliNwW_-XVMzJTOCrV-9f5zgoYkccFnm-3E12GnZvR---5ED6ClZ0Kh-bFJe3uQPFB7uxbF6Erkv1rcLqLQBFBXaG-lKgOA_b9u9M3kvRTuA38TrDnJugnL4y-FSDQA3YmIY9uNkKrgG_Qs',3);

insert into public.gallery_items (title, category, caption, image, aspect, sort_order) values
('Annual Arangetram 2023','Performance','The culmination of years of rigorous training, captured in a single defining moment on stage.','https://lh3.googleusercontent.com/aida-public/AB6AXuD61a-uqCnsD77y7cjVIbYaG6Akn72d4mkEKzdrhqUG5CASz5t7vBQMxfHZipe2yRtzTl5Cd1k-XTp9xmh_3YxiT62Cb5pzrZpY2a3aIip-gW6D8tQkBc-EgNuLp4-ybUVjRhSCu0cQRZMJVfaB5sIMCspIR1iE4gXC0rS-8A4Zqe-AlUMNJ6l_zp_ZpnSFB4d-NCWgL1elgqvrRxwW9pV-mlL4aExw8U9oLIu7hn5Bbdq6Hq59bjX4oq6ohb7ejAUjeVfLydFXuWh1','aspect-[3/4]',1),
('The Echoes of Shiva','Stage Show','A profound exploration of cosmic dance, blending synchronized rhythm with spiritual narrative.','https://lh3.googleusercontent.com/aida-public/AB6AXuBE6tiU8tpUgLKzc54G0XXGd7Fz08gmhw2VSdXegZXV_u2p0CSrFwtOSIv_r35Bf8NCSE_k5fpL7WOCvLEgxLsvVbjRbDwJ1Tk1C7Z2LX50UAdy0XFJBB0NUZp2YF1VMPnKTXeYh2LJXMmMtUMuwR_WM1YW46UMDoxHYvONIHoRtyNIYUlFMYqvcQ--AMZnP4_nHA_BuFu1t-r1BSyOlW-lpUU-l3vp2_5Cau4zc3l9nld55sQCn9w-kexKKXB1TBqYcAPHCkH1JFQ5','aspect-square',2),
('Abhinaya Studies','Detail','The delicate art of expression, where every glance tells a thousand ancient stories.','https://lh3.googleusercontent.com/aida-public/AB6AXuBr2OpHlQ7mpxN0NhnFlUK_Ud3H_WgdqB8qDzW74EZlOYpkYcQINV9bI_LYJGaPEqDaK_dSHSIyS3zDSlEdTJpjBsovjy8BaRE17Njipb6OQGns86B9daM5bxoqhLc74IN_hxjCXNUPP0cHTY8lp8ZGUY2F7Ue4vMxFzVjJbQMEGbXo2NNiw-rjYXbgnsfOj9aSNux4nK3u01J7e2oGg8Xcc5lEjT3GLptIaEvV-43mipDjmXzN4hSD4U0h2iah5HVlZzk3SGr-snCU','aspect-[4/5]',3),
('Morning Riyaz','Classroom','The foundation of grace built in the quiet hours of disciplined practice.','https://lh3.googleusercontent.com/aida-public/AB6AXuCMcljiFANeG4HsOOvJ1r9ODvSTaXvDeYn-GZIalWbYX8RC14XCyljM-168IL8hfzBbEB4v9PwW6t6g2OJCXKdN2aunIXftTaltF_bTclcdMWP8vTnyPslvFURriEQgSvdIY3Nqy_MmZM16_NTCtuUcYn7l7NloywSiek___J66pECDrw-Ap0cP-dRT3gugyCOubSaeUmocKaL9we6K9LfoU119eLGO8c-7OC-AfRLmRxQyOjkrm9EaKtUFeijJObrDjwHQd2jAliqQ','aspect-[16/9]',4),
('Masterclass with Pandit Rao','Workshop','Passing the torch of tradition through intensive, focused mentorship.','https://lh3.googleusercontent.com/aida-public/AB6AXuAqMmmHQgr6Fo9mfj5TjAInPRzgAPzRsz0qULgD8rrcvgKDQmqRjUHe8ir9bChpnRSN5PNWfHowssYKvVF8I-mjSdH-xAnQ96rB2s7HJrgYVVU_5a0wMJ-kS38j-n28ZjmPl1XfcSazcFzP6GsR9aWm-gkR9AaB1p3eio0AY8oM79gVhlxCoVWLn2Oe1W8YDw_TzpdXK3r3wr-Rqge1FhhwnLkMx6yBQtiQfmFqx4ja_fqWYGmFezmnRuYEOWUlJbedqwB0gTmzPCBo','aspect-[3/4]',5);
